### ISSUE TITLE
Support for IDEA 2023.1

### ISSUE THREAD

**Issue by akupreychik-hfsolutions** [sevdokimov/FriendlyTerminal#11]
Hello! The plugin is very cool, but does not work with the new version of IDEA 2023.1
<img width="623" alt="image" src="https://user-images.githubusercontent.com/126798278/228596138-03c8cb5c-7c38-43b3-a2f3-4edb4173e287.png">

**Comment by sevdokimov** [comment]
Will publish a new version soon.

**Comment by sevdokimov** [comment]
1.1.3 works fine with IDEA 2023.1
