### ISSUE TITLE
Can't run multiline code

### ISSUE THREAD

**Issue by Cosolom** [sevdokimov/FriendlyTerminal#14]
When I inserted code with multiple lines - I can't submit it. "Enter" adding new lines instead of run code

**Comment by sevdokimov** [comment]
I cannot reproduce the problem. Could you provide the text? May be the text contains an unfinished string literal.

**Comment by Cosolom** [comment]
It's not related to text
![FriendlyTerminal](https://github.com/sevdokimov/FriendlyTerminal/assets/11589736/89ed2a57-4465-412e-9955-9f19abf24e54)

**Comment by sevdokimov** [comment]
The problem is in the IntelliJ IDEA language parser, it doesn't recognize `EOF` at the end as a heredoc finish marker.
As a workaround, you can insert a line break between `EOF` and "`". Example:
```
PHP=`cat << 'EOF'
some text
EOF
`; echo $PHP
```

**Comment by Cosolom** [comment]
Thank you!! It works
