### ISSUE TITLE
Restore shortcut for default terminal

### ISSUE THREAD

**Issue by Cosolom** [sevdokimov/FriendlyTerminal#15]
I don't want override main terminal with this one and use FTerminal only for cpecific cases. Is it possible restore shortcut Alt+F12 to default terminal? Now even if I will setup Alt+F12 to ActivateTerminalToolWindow - it's still showing for me FTerminal window. And I don't see option to reconfigurat hotkeys
![изображение](https://github.com/sevdokimov/FriendlyTerminal/assets/11589736/14e8eeeb-8e4b-4063-af09-002772c7385e)

**Comment by sevdokimov** [comment]
Unfortunately, it's impossible now. I'll add an option in the next version.

**Comment by sevdokimov** [comment]
Fixed. You can remove Alt+F12 shortcut from "Terminal Pro" toolwindow.
![image](https://github.com/sevdokimov/FriendlyTerminal/assets/669696/93629162-8ceb-410f-8709-0d75b1098c2b)
