### ISSUE TITLE
Linux rm error while trying to delete files starting with hyphen or double hyphen, "-" or "--"

### ISSUE THREAD

**Issue by Apkovy** [sevdokimov/FriendlyTerminal#18]
There is a bug when trying to delete the file with e.g. this name: "-LLzn9poeiN8cZsG8kI0NfrhwN1FLorR.json".

`rm: invalid option -- 'L'`

The standard solution is to pass the command parameter "--" like this:

`rm -r -- -LLzn9poeiN8cZsG8kI0NfrhwN1FLorR.json`

**Comment by sevdokimov** [comment]
Fixed in 1.1.8
