### ISSUE TITLE
Cannot display Chinese correctly in terminal.

### ISSUE THREAD

**Issue by gerryhjs** [sevdokimov/FriendlyTerminal#2]

**Comment by gerryhjs** [comment]
What display one teriminal:

(venv) hjs@hjs-PC:~$ cd 试试
bash: cd: 试试: 没有那个文件或目录

**Comment by sevdokimov** [comment]
Thanks for the bug reporting.
Fixed. The fix will be available in the next version.

**Comment by sevdokimov** [comment]
I built the [EAP release 1.0.7](https://plugins.jetbrains.com/plugin/18857-friendly-terminal/versions/eap) containing the fix. You can download it and [install it from disk](https://www.jetbrains.com/help/idea/2022.2/managing-plugins.html#install_plugin_from_disk), or add https://plugins.jetbrains.com/plugins/EAP/18857 URL as a [custom plugin repository](https://www.jetbrains.com/help/idea/2022.2/managing-plugins.html#add_plugin_repos) to update plugin to EAP version.
