### ISSUE TITLE
Issue with TerminalPro Plugin in IDEA Startup

### ISSUE THREAD

**Issue by DarkGhast** [sevdokimov/FriendlyTerminal#23]
Encountered an error with TerminalPro plugin in IntelliJ IDEA startup:

Environment:

OS: Windows 10 22H2
Tools: WSL with Ubuntu 22.04.3 LTS
IDEA Version: 2023.1.4
TerminalPro Version: 1.1.8.211
Log file attached.
[idea.log](https://github.com/sevdokimov/FriendlyTerminal/files/14630481/idea.log)

**Comment by sevdokimov** [comment]
Fixed.   1.1.9 should work well.
Thanks for the bug report.
