### ISSUE TITLE
TerminalPro Fails to Execute Commands Correctly

### ISSUE THREAD

**Issue by DarkGhast** [sevdokimov/FriendlyTerminal#24]
Environment:
- OS: Windows 11 23H2
- WSL: Ubuntu 22.04.5 LTS
- IDEA Version: 2024.2.4
- TerminalPro Version: 1.1.10.241 (also tested with 1.1.9.241)

**Description**: Upon using the TerminalPro plugin, the following information is displayed in the text area:
```bash
41f73739
Linux
Ubuntu-22.04
/home/[USERNAME]
[USERNAME]
To run a command as administrator (user "root"), use "sudo <command>".
See "man sudo_root" for details.
```
After entering a command in the input box and pressing Enter, the text area displays information similar to a typical command-line tool:
```bash
[USERNAME]@[HOSTNAME]:/mnt/d/File/Code/[PROJECT_PATH]/[SUBDIRECTORY]$
```
However, after this information is displayed, directly pressing Enter does not execute the command, and the input box reappears. While commands entered in the text area are executed successfully, after the input box refreshes, it does not allow for further command input.

**Additional Notes**: The issue persists even when reverting to an earlier version of the plugin.

Log file attached.
[idea.log](https://github.com/user-attachments/files/17539499/idea.log)

**Comment by sevdokimov** [comment]
The compatibility with IDEA 2024.2.4 was broken.
Fixed in 1.1.11.241
