### ISSUE TITLE
docker integration

### ISSUE THREAD

**Issue by neopaf** [sevdokimov/FriendlyTerminal#25]
AWESOME plugin, thanks!

Please consider Docker integration?
Currently when I dive into Docker container I loose support of Plugin, it's like running `bash` command -- I stay trapped inside until `exit`

Not sure how to properly do that.

One way: intercept docker ps output and when clicked on container, open separate tab, and stand between bash instance inside container and user, like when normal execution.

Please please consider?

(IntelliJ Ultimate Docker plugin can do many interesting things, including starting Terminal tabs, but those tabs are nowhere near as convenient as TerminalPro tabs!)

**Comment by sevdokimov** [comment]
While inside a Docker container, right-click on the console and select Enable UI Session. This action attempts to integrate the current Bash session with TerminalPro. The integration will work if the Docker container supports the necessary commands required by TerminalPro.

**Comment by neopaf** [comment]
this is awesome! worked like a charm. Thanks, Sergey!
спасибо!

**Comment by neopaf** [comment]
![Снимок экрана 2024-11-14 в 16 10 04](https://github.com/user-attachments/assets/e13eaa2b-2a83-4c21-adba-eb9c5cef6d7e)

Can't find a way to assign a keyboard shortcut to it. Any hints?
Thanks in advance!
