### ISSUE TITLE
Keyboard shortcut to switch between UI and command line

### ISSUE THREAD

**Issue by neopaf** [sevdokimov/FriendlyTerminal#28]
Maybe there is one already and I just didn't find it?

If not, please consider adding
* Shift+Tab?
* Alt+Tab?

**Comment by sevdokimov** [comment]
There are 
`Alt+Up` (move the cursor from the command input field to File Panels / Console output)
`Alt+Down` (move the cursor from File Panels / Console output to the command input field)

`Alt+Tab` cannot be used because this shortcut is used by OS to switch windows

**Comment by neopaf** [comment]
Sergey, this is perfect. Thanks again!
