### ISSUE TITLE
UI open .pcap

### ISSUE THREAD

**Issue by neopaf** [sevdokimov/FriendlyTerminal#30]
It is often that I collect .pcap trace inside Docker in a faraway galaxy.

I'd like F4 to download it and open it, just like it does with other IDE-supported files... but open it in app on my computer (Wireshark in this case).

Currently F4 does some screen flickering -- I assume download happens and then IDE claims it can not natively open the file and that error goes back to plugin and then nothing.
Please consider then opening file using system association? (or maybe ask IDE to do that for plugin?).

![Снимок экрана 2024-11-28 в 15 41 02](https://github.com/user-attachments/assets/2d7cbbf6-00f3-49e1-87ee-2ab57ae8d974)

**Comment by sevdokimov** [comment]
Fixed in 1.1.11.241: "Open File" will open the downloaded file using the default application configured in OS if IDEA cannot open the file.  Let me now if something works wrong.

**Comment by neopaf** [comment]
both F4 and Doubleclick work flawlessly, thanks, Sergey!
