### ISSUE TITLE
use with WSL?

### ISSUE THREAD

**Issue by JiaRG** [sevdokimov/FriendlyTerminal#5]

**Comment by sevdokimov** [comment]
I'm working on support WSL right now. The next version will work on Windows if there is a Linux distribution in WSL.

**Comment by sevdokimov** [comment]
I have uploaded EAP version of the plugin that supports WSL: https://plugins.jetbrains.com/plugin/18857-friendly-terminal/versions/EAP/284403
Appreciate any feedback.

**Comment by sevdokimov** [comment]
@JiaRG  1.1.0 is released, it supports WSL.
